[import "std"];

[namespace foo,

    [namespace bar,
        @global @static
        text := "Hello, world!";    

        [function print, ()[void],
            .std.print(line=..text);
        ];
    ];


    [function print, ()[void],
        .std.print(line=..bar.text);
    ];

];

[function print, ()[void],
    .std.print(line=..foo.bar.text);
    .std.print(line=.foo.bar.text);
];