[import "std"];

[function print, ()[void],
    ..std.print(line=..foo.bar.text);
];

[namespace foo,

    [namespace bar,
        [global][static]
        text:= "Hello, world!";

        [function print, ()[void],
            ..std.print(line=text);
        ];
    ];


    [function print, ()[void],
        ..std.print(line=..foo.bar.text);
    ];
];