[import "std"];

[table foo,

    [table bar,
        text := "Hello, world!"ascii;    

        [function print, (><),
            .std.print(line=..text);
        ];
    ];


    [function print, (><),
        .std.print(line=..bar.text);
    ];

];

[function print, (><),
    .std.print(line=..foo.bar.text);
    .std.print(line=.foo.bar.text);
];