[enumeration enum,
    float:[binary32];
    int:[signed];
    str:^[utf8];
]

val := enum.float(1.234);

result :=
    [match val,
        [case float,
            := float;
        ][case int
            := [binary32]:int;
        ][default
            := 0;
        ]
    ];