[import "std"];

[main
    // the command line arguments are in a slice to null terminated pointer to char.
    // [args] is only usable within [main].
    args :@\[null_terminated]?[char]= [args];

    [for [args], arg:=[value], arg_i:=[index],
        ..std.print(line=
                "arg_" +> arg_i + " is \"" +> arg +> "\""
            );
    ];

    [result] := 0;
];