[template]::{> count_div_2:[unsigned_index], [auto] Element:[symbol] <}
[constraint]::(count_div_2 >= 0 && Element.[is_type])
[class DoubleArray,

    // the problem is this: 
    // there is an [auto] template parameter, so at template declaration time
    // the compiler needs to map the template parameters to parameters in the class layout to prepare for deduction.
    // HOWEVER, the count of elements in the data is determinate based on a template parameter, but
    // not directly. some math is done to it before its used in the layout.
    // the count can not be evaluated until the actual template argument value is known during specialization.
    // we need to (at declaration time):
    // 1. evaluate all statements after nametag and before layout, and somehow avoid 
    //    issues with template argument values we don't know until specialization
    // 2. map template arguments to layout parameters to prepare for deduction without
    //    caring about values not determinable until specialization time
    // how do we solve this problem?

    // comptime variables are lazily evaluated
    // its is surveyed (added to symbol table) but its not evaluated until the first time its used
    // unevaluated comptime variables are NOT evaluated when mapping arguments for deduction during declaration!
    // instead, the compiler ignores them until specialization.
    [comptime]
    count := count_div_2 * 2; 

    [public][layout_constructor];
    [public][destructor]; 

    // note that Element is [auto], so its still possible to map arguments for deduction at declaration time
    // the value of count cannot be determined until specialization, but this does not stop the mapping during declaration!
    {> data:count#Element <},

];

[main ()[signed_integer],

    my_double_array := DoubleArray{count_div_2=1}([array 1, 2].[emplace]);

    [result] <:= 0;
];