[import "std", std];

[main ()SInt,
    my_array : var\[array 4]#LSInt64 = [array 0, 1, 2, 3, 4].[of LSInt64];
    const_slice : var\slice#LSInt64 = my_array.[slice];
    
    std.print(line=
        "stats: size:" +> my_array.[type].[byte_size] +>
        " count:" +> my_array.[type].[element_count] +>
        " depth:" +> my_array.[type].[bit_depth] +>
        "!");
    [for my_array, index:=index, element:=value, 
        element = element * index.[cast element.[type]];
    ];
    [for my_array.[borrow], index:=index, element:=value, 
        std.print(line="element " +> index +> " is " +> element +> "!");
    ];
    std.print(line="it starts with " +> my_array.[borrow].[at 0] +> "!");

    [result] <:= 0;
];
