[main ()SInt,
    // high and modifiers are compile time values

    static modifier := static;

    // the modifier stored in modifier is ascribed to the variable qualifier
    modifier qualifier := mut;

    my_mut_variable :qualifier\= 0;
    my_mut_variable = 1;

    [result] <:= my_mut_variable;
];

// equivalent to deducing this in c++

[class NumContainer,
    {| num := 0 },

    public [layout_constructor];

    // if reciever is mut, return is ref to mut. is reciver is no_mut, return is ref to no_mut.
    public template::{| auto mut0:Qualifier }
    constraint:mut0.[is_mut_qualifier]
    [proc getNumRef, ()Ref@mut0\SInt=>Ref@mut0\, result,
        result <:= this.num.mut0\[borrow]
    ];

];