[function [main], ()[signed_integer],
    // high and low attributes are compile time values

    [static] low_attribute := [static];

    // the attribute stored in low_attribute is ascribed to the variable high_attribute
    low_attribute high_attribute := [var];

    my_var_variable :high_attribute\= 0;
    my_var_variable = 1;

    [result] <:= my_var_variable;
];

// equivalent to deducing this in c++

[class NumContainer,
    {| num := 0 },


    // if reciever is var, return is ref to var. is reciver is no_var, return is ref to no_var.
    [template]::{| [auto] var:[var_attribute] }
    [function getNumRef, ()$var\[signed_integer]=>$var\,
        [result] <:var\= [this].num.[borrow];
    ];

];