[main ()SInt,
    // high and modifiers are compile time values

    static modifier := static;

    // the modifier stored in modifier is ascribed to the variable qualifier
    modifier qualifier := var;

    my_var_variable :qualifier\= 0;
    my_var_variable = 1;

    [result] <:= my_var_variable;
];

// equivalent to deducing this in c++

[class NumContainer,
    {| num := 0 },

    public [layout_constructor];

    // if reciever is var, return is ref to var. is reciver is no_var, return is ref to no_var.
    public template::{| auto var0:Qualifier }
    constraint:var0.[is_var_qualifier]
    [function getNumRef, ()Ref@var0\SInt=>Ref@var0\, result,
        result <:= this.num.var0\[borrow]
    ];

];