// use auto modifier on template parameters to mark as auto deducing from arguments, reciever, or lvalue

template::{> auto Type:Symbol <}
constraint::Type.[is_type]
[procedure add, 
    // statements before signature are surveyed (not evaluated) at template survey time.
    // everything before signature must be static.
    // the template parameters do not exist at this point. However, you can still reflect on the template layout itself.
    (> a:Type, b:Type <)Split@{ c:Type <}, result,
    // statements after signature are evaluated at specialization implementation time
    result.c <:= a + b;
];

[main ()SInt, result,
    mut0 :SInt = add(1, 2); // Type is SInt

    mut1 := add(1.[as Double], 2.[as Double]); // Type is Double

    mut2 := add(1, 2); // Type is [signed_integer]

    mut3 := add(1.0, 2.0); // Type is Single

    add(2.[as Quadruple], 3.[as Quadruple]).[ignore]; // Type is Quadruple

    result <:= add(1.0, 2.0).[cast]; // Type is Single
];