[import "std"];

[entry
    binary32 := 3.14.[as [binary32]];
    int32 := binary32.[bitwise_cast [signed_integer 32]];
    ..std.print(line=binary32 +> " as integer is " +> int32);
    
    [result] := 0;
];