@no_shallow_copy
[object NoCopy,
    [deep_copier]
    [drop_mover]
    [retain_mover]
];

[function myFunc, (>a:&NoCopy, b:NoCopy<)[signed],
    c :NoCopy= b.[drop_move];
    [result] := 0;
];

[entry_point
    a :NoCopy= NoCopy();
    b :NoCopy= NoCopy();
    num :[signed]= myFunc(a.[borrow], b.[linear_assign]);
    [result] := num;
];