[import "std"];

[function printMe, 
    (|
        snippet:=[callsite].[snippet],
        line:=[callsite].[line],
        column:=[callsite].[column]
    )[void],
    std.print(line=
        "snippet: \"" +> snippet +> "\"" +>
        " line: " +> line +>
        " column: " +> column);
];

[function [main], ()[signed_integer],
    // this will print the following line to the terminal:
    // snippet: "printMe()" line: 18 column: 4
    printMe();

    [result] <:= 0;
];

// [callsite] is only usable for default parameter/property values