[import "std"];

[class Foo, 
    {> [public] string:@[utf8]="Hello, attribute!" <},
];

// NOTE: the compiler enforces that tuples can have only up to one unamed property for any given type.
// if this rule is not followed, this results in a compiler error.
[global][capture]::{ [public] Foo() }
var0 := 1;

[capture]::{ [public] name="Bob", [public] age=25 }
var1 := 0;

[entry

    [static]
    [if ..var0.[symbol].[capture].[has Foo],
        ..std.print(line=..var0.[symbol].[capture].[get Foo].string);    
    ];

    ..std.print(line=
        "Hello, my name is " +> 
        ..var1.[symbol].name +> 
        " and I am " +> 
        ..var1.[symbol].age +> 
        " years old");

    [result] := 0;
];