[import "std", std];

anchor::A
[for 0.<=10, num:=value,
    varname :std.String= std.format(text="VAR" +> num);
    flank::A common capture::{num:=num}
    varname.getSlice().[identify] : SInt = num.[bake];
];

[main ()SInt, result,
    pre [for 0.<=10, pre num:=value,
        pre varname :std.String= std.format(text="VAR" +> num);
        std.print(line=varname.getSlice().[bake] +> " is " +> (varname.getSlice().[identify]) +> "!");  
    ];

    result <:= 0;
];