[import "std"];

[static][anchor]::Loop
[for 0.<=10, num:=[value],
    [static]
    varname :\[var]= ..std.format(text="VAR" +> num);
    [outside_scope]::Loop[global][capture]::{num:=num}
    varname.[identify] :\[var]= num;
];

[entry
    [static]
    [for 0.<=10, num:=[value],
        [static]
        varname :\[var]= ..std.format(text="VAR" +> num);
        ..std.print(line=varname.[borrow] +> " is " +> ..varname.[identify] +> "!");  
    ];

    [result] := 0;
];