[import "std"];

[interface ISpeak,
    [function speak, ()[void]=>,
        std.print(line="I don't speak.");
    ];
];

[class Dog, {},];

[class Cat, {},];

[class Rat, {},
    [function squeak, ()[void]=>,
        std.print(line="Squeak!");  
    ];
];

[adapter A, ISpeak..Dog,
    [function speak, ()[void]=>,
        std.print(line="Woof!");
    ];
];

[adapter A, ISpeak..Cat,
    [function speak, ()[void]=>,
        std.print(line="Meow!");
    ];
];

[adapter A, ISpeak..Rat,
    [use_function speak, Rat.squeak, ()[void]=>$];
];

[interface IGreet,
    [function greet, ()[void]=>,
        std.print(line="I don't greet.");
    ];
];

[adapter A, IGreet..Dog,
    [function greet, ()[void]=>,
        std.print(line="*wags tail*");
    ];
];

[adapter B, ISpeak..Rat,
    [use_function speak, rat.squeak, ()[void]=>];
];

[adapter B, IGreet..Rat,
    [use_function greet, Rat.squeak, ()[void]=>];
];

// everything in adapter polymorph B now added to A
[use_adapter A, B];

[function [main], ()[signed_integer],
    dog := Dog();
    cat := Cat();
    rat := Rat();

    dog.[adapt A, ISpeak].speak();
    dog.[adapt A, IGreet].greet();
    cat.[adapt A, ISpeak].speak();
    cat.[adapt A, IGreet].greet();

    speakAndGreet(animal=dog.[compose A]);
    speakAndGreet(animal=cat.[compose A]);
    speakAndGreet(animal=rat.[compose A]);

    [result] <:= 0;
];

[function speakAndGreet, (> animal:[composition ISpeak, IGreet] <)[void],
    animal.[decompose ISpeak].speak();
    animal.[decompose IGreet].greet();
];