[import "std"];

[interface Speak,
    [method speak, ()[void]=>$,
        ..std.print(line="I don't speak.");
    ];
];

[implicit_drop]
[class Dog,];

[implicit_drop]
[class Cat,];

[implicit_drop]
[class Rat,
    [method sqeak, ()[void]=>$,
        ..std.print(line="Squeak!");  
    ];
];

[implement_interface ..Dog, ..Speak,
    [method speak, ()[void]=>$,
        ..std.print(line="Woof!");
    ];
];

[implement_interface ..Cat, ..Speak,
    [method speak, ()[void]=>$,
        ..std.print(line="Meow!");
    ];
];

[implement_interface ..Rat, ..Speak,
    [use_method speak, ..Rat.squeak, ()[void]=>$];
];

[interface Greet,
    [method greet, ()[void]=$,
        ..std.print(line="I don't greet.");
    ];
];

[implement_interface ..Dog, ..Greet,
    [method greet, ()[void]=>$,
        ..std.print(line="*wags tail*");
    ];
];

[implement_interface ..Rat, ..Speak,
    [use_method speak, ..rat.squeak, ()[void]=>$];
];

[implement_interface ..Rat, ..Greet,
    [use_method greet, ..Rat.speak, ()[void]=>$];
];

[function speakAndGreet, (> animal:$[composition ..Speak, ..Greet] <)[void],
    animal.[compose ..Speak].speak();
    animal.[compose ..Greet].greet();
];

[entry
    dog := ..Dog();
    cat := ..Cat();
    rat := ..Rat();

    dog.[compose ..Speak].speak();
    dog.[compose ..Greet].greet();
    cat.[compose ..Speak].speek();
    cat.[compose ..Greet].greet();

    ..speakAndGreet(animal=dog.[compose ..Speak, ..Greet]);
    ..speakAndGreet(animal=cat.[compose ..Speak, ..Greet]);
    ..speakAndGreet(animal=rat.[compose ..Speak, ..Greet]);
];