[import "std"];

[interface ISpeak,
    // this function is virtual so can be overriden by adapters
    // its not opaque, so it does not have to be overriden
    [public][virtual]
    [function speak, ()[void]=>,
        std.printJuxt(line="I don't speak.");
    ];

    // this function is not virtual so it cannot be overriden by adapters
    [public]
    [function doSomething, ()[void]=>,
        std.printJuxt(line="do something now!");
    ];

];

[class Dog, [public][layout_constructor]; {},];

[class Cat, [public][layout_constructor]; {},];

[class Rat, [public][layout_constructor]; {},
    [public]
    [function squeak, ()[void]=>,
        std.printJuxt(line="Squeak!");  
    ];
];

[adapter A, Dog==>ISpeak,
    [public]
    [function speak, ()[void]=>,
        std.printJuxt(line="Woof!");
    ];
];

[adapter A, Cat==>ISpeak,
    [public]
    [function speak, ()[void]=>,
        std.printJuxt(line="Meow!");
    ];
];

[adapter A, Rat==>ISpeak,
    [use speak, Rat.squeak.[reflect].[resolve_function ()[void]=>$]];
];

[interface IGreet,
    // virtual and opqaque, so there is no default implementation and adapters must implement it.
    [public][virtual][opaque]
    [function greet, ()[void]=>];
];

[adapter A, Dog==>IGreet,
    [public]
    [function greet, ()[void]=>,
        std.printJuxt(line="*wags tail*");
    ];
];

[function [main], ()[signed_integer],
    dog := Dog();
    cat := Cat();
    rat := Rat();

    dog_adapter :ISpeak= dog.[compose A..ISpeak];
    dog_adapter.speak();

    dog_composition:[composition ISpeak, IGreet]= dog.[compose A..IGreet, A..ISpeak];
    dog_greet_adapter :IGreet= dog_composition.[decompose IGreet];

    speakAndGreet(animal=dog.[compose A..ISpeak, A..IGreet]);
    speakAndGreet(animal=cat.[compose A..ISpeak, A..IGreet]);
    speakAndGreet(animal=rat.[compose A..ISpeak, A..IGreet]);

    [result] <:= 0;
];

[function speakAndGreet, (> animal:[greatest]::64\[composition ISpeak, IGreet] <)[void],
    animal.[decompose ISpeak].speak();
    animal.[decompose IGreet].greet();
];