[import "std"];

[template]::{> List:[type_constraint] <}
[function printList, (> list:List <)[void],
    [spin list,
        [weave str:[string_constraint]=[value],
            ..std.print(line="found string: " +> substr);
        ][weave int:[integer_constraint]=[value],
            ..std.print(line="found integer: " +> int);    
        ][weave float:[float_constraint]=[value],
            ..std.print(line="found float: +> float);
        ][weave any:=[value],
            ..std.print(line="found something else: " +> any.[borrow]);
        ];
    ];
];

[entry
    ..printList(
        "hello" +>
        3.14.[as [single]] +>
        0.[as[fast_signed_integer 32]] +>
        [true]);

    [result] := 0;
];