
[global][static]
integer_type   : [integer]    = [unsigned_integer 32];
 
integer_value  : integer_type = 0;

// using type specified in template argument.
[template]::{> Type:[integer] <}
[function addA, (> a:Type, b:Type <)Type,
    [result] := a + b;
];