
[global][static]
integer_type  : [symbol]  = [unsigned_integer 32];
 
integer_value  : integer_type = 0;

[template]::{> Type:[symbol] <}
[constraint]::(Type.[is_integer_type])
[function addA, (> a:Type, b:Type <)Type,
    [result] <:= a + b;
];