[import "std"];

[function [main], ()[signed_integer],
    [result] <:[var]\=0;

    [anchor]::MyWhile
    [while [true],
        [result] = [result] + 1;
        [if [result] == 10,
            MyWhile.[break];
        ];
    ];

    [anchor]::MyWhile
    [while [true],
        [result] = [result] + 1;
        [if [result] == 12,
            [result] = [result] + 2;
            MyWhile.[continue];
        ][else_if [result] == 20,
            MyWhile.[break];
        ];
    ];

    [switch [result]
        ][case 20, 21,
            [result] = 2
        ][default
            [result] = 3;
        ];    

    [anchor]::F
    [fold folded:[signed_integer],
            var := 0;
            [if [true],
                [return]; // if folded not set, must break from outer scope too.
            ];
            folded <:[var]\= var + 1;
            folded = 2; // note that within the fold, folded is var, but outside the fold its [no_var].
            // (folded cannot be mutated after the fold ends)
            [if [true],
                F.[break]; // since folded is set, its ok to break outer scope.
            ];
    ];
];