[import "std"];

[function [main], ()[signed_integer],
    [result] :\[var]=0;

    [anchor]::MyWhile
    [while [true],
        [result] = [result] + 1;
        [if [result] == 10,
            [break MyWhile];
        ];
    ];

    [anchor]::MyWhile
    [while [true],
        [result] = [result] + 1;
        [if [result] == 12,
            [result] = [result] + 2;
            [continue MyWhile];
        ][else_if [result] == 20,
            [break MyWhile];
        ];
    ];

    [switch [result],
    
        [case 21,
            
        ][case 20,
            [fallthrough];
        ][default
            [result] = 0;
        ];    
    ];
];