[import "std"];

[class WithoutDestructor];

[class WithDestructor,
    [destructor
        std.print(line="In destructor!");
        [this].[drop];
    ];
];

[main
    a := WithoutDestructor();
    b := WithoutDestructor();
    c := WithDestructor();
    d := WithDestructor();

    // after drop or destroy, variable is invalidated (can no longer be used)
    a.[drop]; 

    // since b's type has no destructor, behaviour is same as b.[drop]
    b.[destroy];

    // even though c's type has a destructor, its not called
    c.[drop];

    // d's destructor is called
    d.[destroy];

    without := WithoutDestructor();
    with := WithDestructor();

    // if type has no destructor, can do a shallow copy (copies byte for byte)
    copy := without; 

    // this results in a compile error if uncommented because cannot shallow copy types with destructors 
    // other_copy := with;

    [result] := 0;
];

