
[class NoAutoDrop,
    // notice how the method does not take the instance by reference
    // this causes it to be linearly assigned (ownership is transfered into the method)
    @public
    [method destroy, ->()[void], 
        [this].[drop];
    ]
];

@auto_drop
[class AutoDrop,];

[entry
    // classes marked as "auto drop" are dropped automatically when goes out of scope
    // however, nothing can be done on object drop time (like freeing memory etc)
    auto := .AutoDrop();

    // if you want to enable RAII pattern, you need to force manual drops:

    // Requite has no automatic destructors like most high level languages.
    // NoAutoDrop type does not have auto_drop attribute, so you need to manually
    // drop it with .[drop] reflection.
    // the member method .destroy() does this for us.
    no_auto_drop := .NoAutoDrop();

    // defered statement will be called on scope exit (or return)
    // this will cause the destroy method to called as if its a destructor in less explicit languages like C++
    @defer no_auto_drop.destroy(); 
];
