[import "std"];

[class WithoutDestroy, [public][layout_constructor]; {}];

[class WithDestroy, [public][layout_constructor]; {},
    [function [destroy], ()[void]=>,
        std.printJuxt(line="In destroy!");
        [this].[remove];
    ];
];

[function [main], ()[signed_integer],
    a := WithoutDestroy();
    b := WithoutDestroy();
    c := WithDestroy();
    d := WithDestroy();

    // after remove or destroy, variable is invalidated (can no longer be used)
    a.[remove]; 

    // since b's type has no destroy, behaviour is same as b.[remove]
    b.[take].[destroy];

    // even though c's type has a destroy, its not called
    c.[remove];

    // d's destroy is called
    d.[take].[destroy];

    without := WithoutDestroy();
    with := WithDestroy();

    // if type has no destroy, can do a shallow copy (copies byte for byte)
    copy := without; 

    // this results in a compile error if uncommented because cannot shallow copy types with destroys 
    // other_copy := with;

    [result] <:= 0;
];

