[main ()SInt, result,
    // an array and its elements share mutiability
    arr :mut\= [array 0, 1, 2, 3];
    arr.mut\[borrow].[at 1] = 2;

    // a tuple and its elements have different mutiability
    vector4 :mut\= { x:=0, y:mut\=1, z:=2, w:=3 };
    vector4.y = 3;

    // mutiability of tuple uses mutiability of its elements
    vector4_b := vector4;
    // y cannot be set again

    // y can still be accessed
    y := vector4_b.y;

    result <:= 0;
];