[import "std"];

[enumeration MyEnum, [fast_unsigned_integer 32],
    APPLE  :[fast_unsigned_integer 32]  = 0;
    ORANGE :[fast_unsigned_integer 32] = 2;
    GRAPE  :[binary32] = 3;
];

[main
    fruit := MyEnum.APPLE(3);
    [match fruit,
        [case APPLE, apple:=[value].\[var][borrow], 
            apple = apple + 1;
        ][case ORANGE, orange:=[value].\[var][borrow],
            orange = orange * 2;
        ][default
            // do nothing!
        ];
    ];
    value :=
        [match fruit,
            [case APPLE, apple:=[value], 
                [out] := apple;
            ][case ORANGE, orange:=[value],
                [out] := orange.[cast [signed_integer]];
            ][case GRAPE, grape:=[value],
                [out] := grape.[cast [signed_integer]];
            ];
        ];

    [result] := value;
];