[enumeration Fruit, 32,
    APPLE = 0;
    ORANGE = 1;
    GRAPE = 2;
];

[entry_point
    my_fruit :`= Fruit.APPLE;
    [if my_fruit == Fruit.APPLE,
        [result] := 0;    
    ][else
        [result] := 1;
    ];
];