[import "std"];

[enumeration Fruit, [unsigned_integer 32],
	[anchor]::A
	[static][for 0.<100, num:=[value],
		[static] name := ..std.format(text= "MY_FRUIT" +> num);
		[flank]::A name.getSlice().[identify];
	];
];

[entry
	my_fruit := ..Fruit.MY_FRUIT69;
	
	[result] := my_fruit.[cast];
];

