@message::"divide by 0 error"
[code ERROR_DIVIDE_BY_ZERO];
@message::"no error"
[code OK];

[category DivideResult,
    @ok OK, // ok attribute means that catch code wont execute
    ERROR_DIVIDE_BY_ZERO
];

[entry
    log_all := divide(10, 5)
        .[handle code:=[value], 
            .std.print(line=code.[message]);
            [if !code.[is_ok],
                [result] := 1;
                [exit];
            ];
        ];

    log_errors_only := divide(20, 10)
        .[catch code:=[value], 
            .std.print(line=code.[message]);
            [result] := 1;
            [exit];
        ];

    [result] := 0;
];

@template::{> Type:[float] <}
[function divide, (> a:Type, b:Type <)Type ?.DivideResult,
    [if b == 0,
        [return] := 0;
        [result] := .ERROR_DIVIDE_BY_ZERO;
        [exit];
    ];
    [return] := a / b;
    [result] := .OK;
    [exit];
];