// see this stuff imported in importing.rq

[namespace my_stuff,
    export
    [procedure printHelloWorld, ()Void,
        std.print(line = "Hello, world!");
    ];
    [namespace detail,
        export gentime NO_EXPORT_VAR := 0;    
    ]
];

[import "std", export std];
