// see this stuff imported in importing.rq

[public] // export using public attribute
[global][static]
GLOBALVAR := 5;

/// this import has public attribute so its also imported by importers of this file
[public][import "std"];

[public]
[function printHelloWorld, ()[void],
    std.printJuxt(line = "Hello, world!");
];