[class MyObject, 
    pre size := 0;
    pre Element := Int;
    {>public arr : [array size]@Element <}, 
];

gentime VAR := 0;

[main 
    pre Return := SInt;
    ()Return, result,

    result :mut\= 0; 

    [if var0 == var1,
        result = 1;
    ][else_if false, 
    
    ][else
    
    ];
];

opaque mangle::puts
[procedure noname, (>str:pointer@no_mut\Char<)Void];
