[class MyObject, 
    static size := 0;
    static Element := Int;
    {>public arr : [array size]@Element <}, 
];

compile_time VAR := 0;

[main 
    static Return := SInt;
    ()Return,

    [result] :var\= 0; 

    [if var0 == var1,
        [result] = 1;
    ][else_if false, 
    
    ][else
    
    ];
];

opaque mangle::puts
[function noname, (>str:pointer@no_var\Char<)Void];
