[class MyObject, 
    static size := 0;
    static Element := Int;
    {>public arr : [array size]@Element <}, 
];

compile_time VAR := 0;

[main 
    static Return := SInt;
    ()Return, result,

    result :mut\= 0; 

    [if mut0 == mut1,
        result = 1;
    ][else_if false, 
    
    ][else
    
    ];
];

opaque mangle::puts
[procedure noname, (>str:pointer@no_mut\Char<)Void];
