
[namespace example,
    [template]::{> Type:[type], LENGTH:[unsigned_index] <}
    [function getElementCount, ()[unsigned_index]=>$LENGTH#Type,
        [result] := LENGTH;
    ];

    [class Foo,];

    [function bar, ()[void]=>$Foo,
    
    ];
];

[function [main], ()[signed_integer],
    my_array :5#[signed_integer]= [array 0, 1, 2, 3, 4].[of [fast_signed_integer 32]];

    // call extension function
    my_array.[borrow]->example.getElementCount().[ignore];
    
    // construct variable of type declared in same table as extension functions
    foo := example.Foo();

    [result] := 0;
];