
[namespace example,
    @template::{> Type:[type], LENGTH:[integer].[unsigned].[index_depth] <}
    [extension_function getElementCount, LENGTH#Type, (><)[integer].[unsigned].[index_depth],
        [result] := LENGTH;
    ];

    @template::{> Type:[type], LENGTH:[integer].[unsigned].[index_depth] <}
    [extension_method getElementCount, &LENGTH#Type=>(><)[integer].[unsigned].[index_depth] ,
        [result] := LENGTH;
    ];

    @auto_drop
    [class Foo,];

    [extension_method bar, &Foo=>(><)[void],
    
    ];
];

[entry
    my_array :5#[signed]= [initializer_list 0, 1, 2, 3, 4].[of [integer].[signed].[fast 32]];

    // call extension function
    {} = my_array.[type]->.example.getElementCount();
    // call extension method
    {} = my_array.[borrow]->.example.getElementCount();
    
    // construct variable of type declared in same table as extension functions
    foo := .example.Foo();

    // call extension function
    foo.[borrow]->.example.bar();
];