[import "std"];

[function [main], ()[signed_integer],
    [fold int:[signed_integer], float:[single],
        int <:= 4;
        float <:= 3.14;
    ];

    [result] <:= int + float.[cast [signed_integer]];
];