opaque mangle::myForwardedAdd
[function myForwardedAdd, (> a:[single], b:[single] <)[single],];

// you have to write the signature again, and it has to be identical
[implement_function myForwardedAdd, (> a:[single], b:[single] <)[single],
    [result] := a + b;
];

[entry
    .std.print(
        "the result is {
            .myForwardedAdd(
                1.0,
                2.0)
        }");
];