opaque mangle::myForwardedAdd
[function myForwardedAdd, (> a:Single, b:Single <)Single];

// you have to write the signature again, and it has to be identical
[implement_function myForwardedAdd, (> a:Single, b:Single <)Single,
    [result] <:= a + b;
];

[main ()SInt, result,
    std.print(
        "the result is " +>
        myForwardedAdd(
            1.0,
            2.0));

    result <:= 0;
];