[procedure myProcedure, ( 
        positional:Single=0.0,
        >positional_and_named:Single=0.0<,
        named:Single=0.0,
        |locked:Single=0.0
    )Single, result,
    result <:= 
    (positional + positional_and_named + named + locked);
];

[procedure myOtherProcedure, ( 
        positional:Single=0.0,
        >positional_and_named:Single=0.0<,
        named:Single=0.0,
        |locked:Single=0.0
    )Single, result,
    result <:= (positional + positional_and_named + named + locked);
];

[procedure myThirdProcedure, ( 
        positional:Single=0.0,
        >positional_and_named:Single=0.0<,
        named:Single=0.0 * 0.0,
        |locked:Single=0.0
    )Single, result,
    result <:= (positional + positional_and_named + named + locked);
];

[procedure myFourthProcedure, ( 
        first_arg:single=0.0,
        >positional_and_named:single=0.0<,
        named:single=0.0,
        |locked:single=0.0
    )Single, result,
    result <:= (positional + positional_and_named + named + locked);
];


[main ()SInt, result,
    // calling directly from myProcedure
    // default values are used
    // locked parameters cannot be set
    // parameter marks apply
    a := myProcedure();
    b := myProcedure(1.0);
    b := myProcedure(1.0, 2.0);
    c := myProcedure(1.0, positional_and_named);
    d := myProcedure(1.0, named=2.0);
    e := myProcedure(1.0, named=2.0, positional_and_named=3.0);
    f := myProcedure(1.0, 2.0, named=3.0);
    g := myProcedure(1.0, positional_and_named=2.0, named=3.0);

    // call from a pointer to myProcedure
    ptr :\mut= myProcedure.[procedure_address];
    // you can call from ptr just like myProcedure
    h := ptr(1.0, 2.0, named=3.0, locked=4.0);
    i := ptr();
    j := ptr(1.0);
    k := ptr(1.0, 2.0);
    l := ptr(1.0, positional_and_named);
    m := ptr(1.0, named=2.0);
    n := ptr(1.0, named=2.0, positional_and_named=3.0);
    o := ptr(1.0, 2.0, named=3.0);
    p := ptr(1.0, positional_and_named=2.0, named=3.0);

    // can assign different function to variable if its [mut] and has EXACTLY the same signature.
    // the default values need to have identical expressions when situated.
    ptr = myOtherProcedure.[procedure_address];
    ptr();

    // type is different even if default value evaluates to the same result.
    // ptr = myThirdProcedure.[procedure_address]; 
    // this would result in compile error because named parameter's default value is wrong.
    // its wrong even though it still evaluates to 0.
    // need to use signature_cast
    ptr = myThirdProcedure.[procedure_address].[signature_cast];
    ptr();
    
    // need to cast if parameters are named differently
    ptr = myFourthProcedure.[procedure_address].[signature_cast];
    ptr();

    result <:= 0;
];