[import "stde"];

[function myFunc, (>a:[signed], b:[signed]<)[signed],
    [if a > b,
        std.print(line="a is greater than b");
    ][else_if b > a,
        std.print(line="b is greater than a");
    ][else 
        std.print(line="a and b are equal");
    ];
    [result] := a + b;
];

[entry_point
    std.print(line="the result is {myFunc(1, 2)}");
];