
@static
concrete_integer_type      : [integer].[concrete] = [integer].[unsigned].[exact 32];

@static
generic_integer_type       : [integer].[generic]  = [integer].[unsigned];

@static
generic_or_concrete_integer_type   : [integer].[generic_or_concrete] = [integer].[unsigned];
 
integer_value_of_any_type  : [integer]            = 0;

// using type specified in template argument.
// this garuntees the type is the same for all args and return.
@template::{> Type:[integer].[concrete] }
[function addA, (> a:Type, b:Type )Type,
    [result] := a + b;
];

// using generic type
// the two arguments may be of different types, which is why static_cast is needed.
[function addB, (> a:[integer], b:[integer] )[integer],
    [result] := a + b.[static_cast a.[type]];
];