template::{ Type:Symbol <}
constraint::(Type.[is_type])
require::(b != 0)
ensure::(result >= 0)
[function divideSquare, ( a:Type, b:Type <)Type,
    divide_result := a / b;
    square := divide_result * divide_result;
    result <:= square;
];

[main ()Int,
    a := divideSquare{Int}(6, 2);
    
    result <:= 0;
];