[template]::{| Type:[symbol] }
[contraint]::(Type.[is_numeric_type])
[function divideSquare, 
    [require]::(b != 0)
    [ensure]::([result] >= 0)
    ( a:Type, b:Type <)Type,
    divide_result := a / b;
    square := divide_result * divide_result;
    [result] := square;
];

[entry
    a := ..divideSquare(6, 2);
    
    [result] := 0;
];