// all function returns must be handled at least with an ignore. there is no way to mark a return as automatically ignorable in a function signature.

[function nodiscard, ()[fast_signed_integer 32],
    [result] := 0;
];

[mangle]::main
[function [noname], ()[signed_integer],
    // function returns must be used or this will cause compile error. however, ignore reflection can be used to ignore it.
    nodiscard().[ignore]; 

    [result] := 0;
];