[function nodiscard, ()::[fast_signed_integer 32],
    [result] := 0;
];

[function maydiscard, $may_discard ()::[fast_signed_integer 32],
    [result] := 0;
];

[entry

    // function returns must be used or this will cause compile error. however, ignore reflection can be used to ignore it.
    nodiscard().[ignore]; 

    // when signature has may_discard attribute, no need to ignore explicitly.
    maydiscard(); 

    [result] := 0;
];