// see exporting.rq for what is being imported

[import "exporting", my_stuff.[without detail], std];  // notice there is no .rq file extension

[main ()SInt, result,
    my_stuff.printHelloWorld(); // this function is from exporting.rq
    std.print(line="Goodbye, world!"); // std was imported by exporting.rq
    result <:= 0;
];