// see exporting.rq for what is being imported

[import "exporting"] // notice there is no .rq file extension

[main ()Int,
    printHelloWorld(); // this function is from exporting.rq
    std.print(line="Goodbye, world!"); // std was imported by exporting.rq
    [result] <:= COMMONVAR; // COMMONVAR is from exporting.rq
];