// see exporting.rq for what is being imported

[import "exporting"] // notice there is no .rq file extension

[function [main], ()[signed_integer],
    printHelloWorld(); // this function is from exporting.rq
    std.printJuxt(line="Goodbye, world!"); // std was imported by exporting.rq
    [result] <:= GLOBALVAR; // GLOBALVAR is from exporting.rq
];