[import "std"];

@may_parent
[class Parent,
    
    [method myFunc, &=>(><),
        .std.print(line="in parent");
    ];
    
    @virtual
    [method myFuncB, &=>(><),
        .std.print(line="in parent");
    ];
    
    [constructor];
];

[class Child,
    {> 
        @parent parent := .Parent() 
    <},
    
    @public
    [use parent.myFunc];
    
    @public
    @override::parent.myFuncB
    [method myFuncB, &=>(><),
        .std.print(line="in child");
    ];

    @public 
    [constructor];
];

[entry
    parent := .Parent();
    child := .Child();

    parent.[borrow].myFunc();
    child.[borrow].myFunc();
    parent.[borrow].myFuncB();
    child.[borrow].myFuncB();
];