[import "std"];

[abstract]
[class Abstract,
    [abstract]
    [method myFuncB, ()[void]=>$,];
];

[may_parent][implicit_drop][may_copy]
[class Parent,
    {>
        [parent] abstract :..Abstract
    <},
    
    [method myFunc, ()[void]=>$,
        ..std.print(line="in parent");
    ];
    
    [virtual][override]::abstract.myFuncB
    [method myFuncB, ()[void]=>$,
        ..std.print(line="in parent");
    ];
];

[implicit_drop][may_copy]
[class Child,
    {> 
        [parent] parent := ..Parent() 
    <},
    
    [public]
    [use myFunc, parent.myFunc];
    
    [public]
    [override]::parent.myFuncB
    [method myFuncB, ()[void]=>$,
        ..std.print(line="in child");
    ];
];

[entry
    parent := ..Parent();
    child := ..Child();

    parent.[borrow].myFunc();
    child.[borrow].myFunc();
    parent.[borrow].myFuncB();
    child.[borrow].myFuncB();
];