[import "std"];

[template]::{> List:[symbol] <}
[function printList, (> list:List <)[void],
    ..std.print(line="begin!");
    [spin list,
        ..std.print(line="weave!");
        [weave [value].[type].[is_integer_type], int:=[value],
            ..std.print(line="found integer: " +> int);    
        ][weave [value].[type].[is_float_type], float:=[value],
            ..std.print(line="found float: " +> float);
        ][weave [true], any:=[value],
            ..std.print(line="found something else: " +> any.[borrow]);
        ];
    ];
    ..std.print(line="end!");
];

[entry
    ..printList(
        "hello" +>
        3.14.[as [single]] +>
        0.[as[fast_signed_integer 32]] +>
        [true]);

    ..printList(
        "this" *> 
        "is" *>
        "one" *>
        "string" *>
        "literal");

    [result] := 0;
];