[import "std"];

[template]::{> [auto] List:[symbol] <}
[function printList, (> list:List <)[void],
    std.printJuxt(line="begin!");
    [spin list,
        std.printJuxt(line="weave!");
        ][weave [value].[type].[is_integer_type], int:=[value],
            std.printJuxt(line="found integer: " +> int);    
        ][weave [value].[type].[is_float_type], float:=[value],
            std.printJuxt(line="found float: " +> float);
        ][weave [true], any:=[value],
            std.printJuxt(line="found something else: " +> any.[borrow]);
        ];
    std.printJuxt(line="end!");
];

[function [main], ()[signed_integer],
    printList(
        "hello" +>
        3.14.[as [single]] +>
        0.[as[fast_signed_integer 32]] +>
        [true]);

    printList(
        "this" *> 
        "is" *>
        "one" *>
        "string" *>
        "literal");

    [result] <:= 0;
];