// NOTE: types in requite can have no implicit conversions, even from literals!
// If you want to change from one numeric type to another you always must cast.

// NOTE: no implicit casting between types even if they share the same underlying type.

[include "string.h"];

[entry
    // if no type specified, it defaults to fastest signed of at least 32-bits
    a := 0; // [signed].[fastest_bits 32] // could be larger than 32 bits on some platforms!

    // can cast to make more specific
    // if casted immediatly, then the literal is treated as the casted type.
    b := [signed].[exact_bits 32]:0; // signed integer type of exactly 32 bits no matter what

    // can use suffixes to bake type info into the integer itself
    // this is more straight forward
    c := 0u;     // [unsigned].[fastest_bits 32]
    d := 0ue64;  // [unsigned].[exact_bits 64]
    e := 0uf64;  // [unsigned].[fastest_bits 64]
    f := 0ul128; // [unsigned].[least_bits 128]   // smallest native unsigned integer with at least 128-bits
    // there are special types for working with memory across platforms
    g := 0udx // [unsigned_index] // unsigned type the size of indexes used for memory address indexing
    h := 0uad // [unsigned_address] // unsigned type the size of memory addresses

    // integer literals can be written with an alternate base in the format <base>x<digits>
    // bases in requite can be anything from 2 to 64
    // If the base is over 35, then the digits are case sensitive
    i := 16xDeadBeef; // hexadecimal. casing does not matter
    j := 48xaAbBcCdD; // 48-decimal. capital letters have different values than lowercase
    k := 64xa3BzzZ!fe?3g // 64-decimal. notice that ! and ? are now treated as digits (digit value 62 is ? and 63 is !)
    
    // suffixes in literals with a base go after the base.
    l := 2ue32x1001010111; // suffix makes it [unsigned].[exact_bits 32]

    // underscores among integer literal digits are ignored
    m := 16ue8xF_F;
    n := 1_000_000_000ue64;

    // the default encoding is utf8
    o := 'A'; // [utf8]

    // others can be used with a suffix after the closing quote mark
    p := 'B'ascii; // [ascii]

    // strings are null terminated fat pointers to utf8 by default and have suffixes that work the same way
    q := "asdf"ascii; // $null_terminated ^[ascii]

    // if assigned to a mutable variable, the null_terminated attribute goes away unless explicitly reassigned
    // in practice, this limits how you can manipulate the value so you cant break its null_terminated status
    r :$null_terminated `= "asdf"; // $null_terminated `^[utf8]    

    // it stays if a const address is created
    s := "asdf"ascii.[address]; // $null_terminated *[ascii]

    // function arguments can require a null terminated pointer, for example
    [function length, (>ptr:$null_terminated ^[utf8]<),
        [result] := [c].strlen(ptr.[data_address]); // calling strlen from libc
    ];

    // floating point numbers work similarly to integers
    // numbers with a decimal points automatically become floating point
    // however, exact, least, and fastest sizes are not supported
    // you can use best, which may pick a smaller float type if there are none that work
    t := 0.0;    // [float].[best_bits 32]  // its a float because of the decimal point
    u := 0.0f;   // [float].[best_bits 32]  // explicit float suffix
    v := 0f;     // [float].[best_bits 32]  // no decimal point, but we make it a float with the suffix
    w := 128ff16 // [float].[best_bits 16]

    // it might be beneficial to be explicit about what types of floats you want to use instead
    x := 0binary16;   // [binary16]
    y := 100bfloat16; // [bfloat16]

    // boolean types are simple
    z := [true]; // [false]
];