[import "std"];

[entry

    // all of these loops are equivalent

    // equal limit interval
    [for (0.==9).[each], value:=[value],
        .std.print(line="value is {value}");    
    ]

    // less limit interval
    [for (0.<10).[each], value:=[value], 
        .std.print(line="value is {value}");    
    ];

    // interval
    [for (0.<10.+1).[each], value:=[value], 
        .std.print(line="value is {value}");    
    ]

    [scope
        // while loop    
        value :`= 0.[as [integer].[signed].[fast 32]];
        [while value < 10,
            .std.print(line="value is {value}");   
            value = value + 1;
        ];
    ];

    // array element range
    [for [initializer_list 0, 1, 2, 3, 4, 5, 6, 7, 8, 9].[each], value:=[value],     
        .std.print(line="value is {value}");
    ];

    // ranger range
    [class MyClass,
        {> 
            @public data:10#[integer].[signed].[fast 32]=[initializer_list 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        <},

        @public
        [ranger each, &=>(><)$ranging [integer].[signed].[fast 32],
            [for [this].data.[each], value:=[value].[borrow], 
              [range_over 
                value
              ];
            ];
        ];
    ];
    class := MyClass();
    [for class.[borrow].each(), value:=[value], 
        .std.print(line="value is {value}");
    ];

    [if (0.<10)->.std.getContains(5),
        .std.print(line="5 is within interval over 0 to 10");
    ];
];