[import "std", std];

[main ()SInt, result,

    // all of these loops are equivalent

    // equal limit interval
    // the lvalue "value" is name of variable, the rvalue "value" is an 
    // expaneded _SneakyMacro. See stellarscope.rq!
    [for 0.!=9, value:=value, 
        std.print(line="value is " +> value);    
    ];

    // less limit interval
    [for 0.<10, value:=value, 
        std.print(line="value is " +> value);    
    ];

    // interval
    [for 0.<10.+1, value:=value, 
        std.print(line="value is " +> value);    
    ];

    [scope
        // while loop    
        value : mut\ = 0;
        [while value < 10,
            std.print(line="value is " +> value);   
            value = value + 1;
        ];
    ];

    // array element range
    [for [array 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], value:=value,     
        std.print(line="value is " +> value);
    ];

    [if (0.<10)->std.getContains(5),
        std.print(line="5 is within interval over 0 to 10");
    ];

    result <:= 0;
];