[entry_point
    num :[signed]= 0;
    pointer :*[signed]= num.[address];
    copy_of_num :[signed]= pointer.[content];
    reference_to_num :&[signed]= pointer.[content].[borrow];

    mutable_array :`5#[signed]= `#:{1, 2, 3, 4, 5};
    reference :&5#[signed]= array.[borrow];
    reference_to_mutable :&`5#[signed]= array.`[borrow];
    mutable_reference :`&5#[signed]= `:array.[borrow];
    mutable_reference_to_mutable :`&`5#[signed]= `:array.`[borrow];
    fat_pointer :^[signed]= array.[view];
    fat_pointer_to_mutable :^`[signed]= array.`[view];
    mutable_fat_pointer :`^[signed]= `:array.[view];
    mutable_fat_pointer_to_mutable :`^`[signed]= `:array.`[view];
    array_of_array :1#5#[signed]= array.[singleton];
    fat_pointer_to_array :^5#[signed]= array.[singleton].[view];
    sub_fat_pointer :^[signed]= array.[slice 2.==4]; // contains {3, 4, 5}
    sub_fat_pointer_to_mutable :^`[signed]= array.`[slice 2.<4]; // contains {3, 4}
    reference_to_sub_array :&3#[signed]= array.[array_slice 2.==4]; // contains {3, 4, 5}
    reference_to_mutable_sub_array :&`2#[signed]= array.`[array_slice 2.<4]; // contains {3, 4}
];