[entry_point
    num := 0;
    pointer := num.[address];
    copy_of_num := pointer.[content];
    reference_to_num := pointer.[content].[refer];

    array := #`:{1, 2, 3, 4, 5};
    reference := array.[refer];
    reference_to_mutable := array.`[refer];
    fat_pointer := array.[view];
    fat_pointer_to_mutable := array.`[view];
]