[import "std"];

@may_copy @auto_drop @may_copy
[class MyClass,

  @public
  [method destroy, ()::[void]=>,
    // explicit drop without destroy
    [this].[drop];

    // NOTE: .[drop] reflection only usable in member functions and methods.
  ];

];

// This class has stable_address attribute, so it cannnot be moved to a new memory address
// Also it does not have auto_drop attribute, so it must be manually dropped
@may_copy @stable_address
[class MyPinned,
  @public
  [method destroy, ()::[void]=>,
    // explicit drop without destroy
    [this].[drop];

    // NOTE: .[drop] reflection only usable in member functions and methods.
  ];
];

[entry
  class :`= .MyClass();
  copy := class;
  reference := class.[borrow];
  reference_to_mutable := class.`[borrow];
  pointer := class.[address];
  pointer_to_mutable := class.`[address];
  copy_value_at_pointer := pointer.[content];
  non_destructive_move := class.`[borrow]->.std.extract();
  destructive_move := class.[move];
  // class was dropped
  destructive_move.[move].destroy(); // linear assign into destructor method
  // non_destructive_move is auto dropped here
  pinned := MyPinned();
  // moved := pinned.[move]; // this move would cause a compiler error because moving to a new memory location and and it has stable_address attribute
  pinned.[move].destroy(); // this move is valid because the memory location does not change
];