[main ()SInt, result,
    // specify type in binding
    mut0 : SInt32 =0;

    // can also cast literal using .[as]
    // binding type is inferred from the rvalue
    mut1 := 0.[as SInt32];

    // if no type is specified, integer literal is infered to Int. size is dependent on platform.
    mut2 := 0;

    // for unsigned integers at least 32 bits in size:
    // exact is UInt32
    // fastest is FUInt32
    // min bits with regsiter size on platform is LUInt32
    mut3 : UInt32 =0;
    mut4 : FUInt32 =0;
    mut5 : FUInt32 =0;

    // special sizes:
    // SSize and USize for memory address sized integers
    // SIndex and UIndex for address index sized integers
    mut6 : SSize =0;
    mut7 : USize =0;
    mut8 : UIndex =0;
    mut9 : UIndex =0;

    // there are platform-changing float types:
    // Half Single Double Quadruple
    mut10 : Half =0;
    mut11 : Single =0;
    mut12 : Double =0;
    mut13 : Quadruple =0;

    // you can use specific floating point formats instead:
    // Binary16 Binary32 Binary64 Binary128 BFloat16
    mut14 : Binary16 =0;
    mut16 : Binary32 =0;
    mut17 : Binary64 =0;
    mut18 : Binary128 =0;
    mut19 : BFloat16 =0;

    // integers can be written with any base from 2 to 64
    // bases above 35 are case sensitive
    mut20 : UInt64 =2x101;
    mut21 : UInt64 =16xDeadBeef;
    mut22 : UInt512 =64xabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789?!;

    // underscores in integers are ignored
    mut23 : UInt128 =16xBeef_Babe;

    // floats can be written with decimal
    mut24 :=3.14; // type is Single, which depends on platform

    
    // if you want to convert between types, you need to use casts
    // see casts.rq

    result <:= 0;
];