[import "std"];

@may_copy @may_move
[class MyClass,
    {>
        :x = 0,
        :y = 0,
        :z = 0
    <},

    @public
    [constructor];

    @public
    [constructor (>[signed]:x, [signed]:y, [signed]:z<),
        {x=x, y=y, z=z},
    ];

    @public
    [method getTotal, &=>(><)[signed],
        :[result] = [this].x + [this].y + [this].z;
    ];

    @public
    [function add, (>MyClass:a, MyClass:b<)MyClass,
        :[result] =
            MyClass(
                a.x + b.x,
                a.y + b.y,
                a.z + b.z
            );
    ];
];

[entry_point

    :a = MyClass();
    :b = MyClass(1, 2, 3);

    std.print(line="a total:{a.[borrow].getTotal()}");

    :added = MyClass.add(a, b);

    :[exit_code] = added.[borrow].getTotal();
];