[import "std"];

[class MyClass,
    {>
        public x : fsi32 = 0,
        public y : fsi32 = 0,
        public z : fsi32 = 0
    <},

    public [layout_constructor];

    public
    [function fromScalar, (> scalar:fsi32 <)MyClass,
        [result] <:= MyClass(scalar, scalar, scalar);    
    ];

    public
    [function getTotal, ()fsi32=>$,
        [result] <:= [this].x + [this].y + [this].z;
    ];

    public
    [function add, (>a:MyClass, b:MyClass<)MyClass,
        [result] <:=
            MyClass(
                a.x + b.x,
                a.y + b.y,
                a.z + b.z
            );
    ];
];

[main ()si,

    a := MyClass();
    b := MyClass(1, 2, 3);
    c := MyClass.fromScalar(4);

    std.printJuxt(line="a total:{a.[borrow].getTotal()}");

    added := MyClass.add(b, c);

    [result] := added.[borrow].getTotal();
];