[import "std"];

@may_copy @may_move
[class MyClass,
    {>
        x : [signed_least_bits 32] = 0,
        y : [signed_least_bits 32] = 0,
        z : [signed_least_bits 32] = 0
    <},

    @public
    [function fromScalar, (> scalar:[signed_least_bits 32] <)MyClass,
        [result] := MyClass(scalar, scalar, scalar);    
    ];

    @public
    [method getTotal, &=>(><)[signed_least_bits 32],
        [result] := [this].x + [this].y + [this].z;
    ];

    @public
    [function add, (>a:MyClass, b:MyClass<)MyClass,
        [result] :=
            MyClass(
                a.x + b.x,
                a.y + b.y,
                a.z + b.z
            );
    ];
];

[entry

    a := .MyClass();
    b := .MyClass(1, 2, 3);
    c := .MyClass.fromScalar(4);

    .std.print(line="a total:{a.[borrow].getTotal()}");

    added := .MyClass.add(b, c);

    [result] := added.[borrow].getTotal();
];