
// the layout of this prototype is unknown. it can be defined later if the class is fully implemented.
[opaque][mangle]::MyClass
[class MyClass, [unknown]];

[opaque][mangle]::getInstanceRef
[function getInstance, ()$MyClass];

// when this class fully implemented, it can be a maximum of 64 bits in size
[opaque][mangle]::SizedClass
[class SizedClass, [greatest 64]\[unknown],

    [opaque]
    [function doSomething, ()[void]=>$[var]\];
];

[opaque][mangle]::getSized
[function getSized, ()MyClass];

[function [main], ()[signed_integer],
    ref := getInstanceRef().[borrow];
    sized := getSized(); 
    // Sized uses 64 bits of memory in the stack.
    // However, the class layout is unknown.
    // Its not possible to access members directly.
    sized.[var]\[borrow].doSomething();
    [result] <:= ref.[address].[cast];
];