// parameter marks are ways of declaring rules for how functions can be called

// > mark before a parameter means that parameter and every parameter after may be named
// < mark after a parameter means that parameter and every parameter before may be positional
// | mark before a parameter means that parameter and every parameter after may not be set (and will use default value)

// > must come before < if both exist. If | exists, it must be after all other parameter marks that exist.

// when parameters must be named and never positional, you can overload function by parameter name alone (types can be the same)

[import "std", std];

[proc allPositional, (arg0:Binary32, arg1:Binary32 <)Void];

[proc allNamed, (> arg0:Binary32, arg1:Binary32)Void];

[proc namedOrPositional, (> arg0:Binary32, arg1:Binary32<)Void];

[proc nonSettable, (| a:=0, b:=1 )Void];

// a must be positional
// b can be either named or positional
// c must be named
// d can not be set and will use default value (3)
[proc mix, (a:=0,> b:=1 <, c:=2, | d:=3)Void];

// parameter marks work the same way for template layouts and class layouts
template::{a:=0, > b:=1 <, c:=2, | d:=3}
[class MyTemplateClass,     
    {},
    public[layout_constructor];
];

[class MyClass, 
    {a:=0, > b:=1 <, c:=2, | d:=3},
    public[layout_constructor];
];

[main ()SInt, result,
    template : MyTemplateClass{0, b=1, c=2} = MyTemplateClass{0, b=1, c=2}();
    class : MyClass = MyClass(0, b=1, c=2);
    result <:= 0;
];