[class Partialable,
    {>
        public partial_mutate property_a : FSInt32 = 0,
        public property_b : FSInt32 = 0
    <},

     public[layout_constructor];
];

[main ()SInt, result,
    // compile_time variables must have variables of no_mut type becauese
    // they are constant:
    compile_time never_mut : no_mut\ = Partialable();

    // all properties are mut for fully mut values:
    fully_mut : mut\ = Partialiable();

    // only properties marked with [partial_mut] are mut for partially mut values:
    partially_mut : partial_mut\ = Partialable();

    result <:= 0;
];