[class Partialable,
    {>
        [public][partial_mutate] property_a : [fast_signed_integer 32]= 0,
        [public] property_b : [fast_signed_integer 32] = 0
    <},
];

[function [main], ()[signed_integer],
    // no properties are var for constant values:
    constant := Partialable();

    // all properties are var for fully var values:
    fully_var : \[var] = Partialiable();

    // only properties marked with [partial_var] are var for partially var values:
    partially_var : \[partial_var] = Partialable();

    [result] <:= 0;
];