

[opaque][mangle]::malloc
[function malloc, (size:[unsigned_address]<)?\[var][void]];

[opaque][mangle]::free
[function free, (ptr:?\var[void]<)[void]];

[template]::{Type:[symbol]<}
[constraint]::(Type.[is_type])
[class UniquePtr,
    { [private] ptr:?\[var]Type <},

    [public][inline]
    [template]::{Placement:[symbol]<}
    [constraint]::Placement.[is_placement_type Type]
    [function create, 
        (placement:Placement<)\[var]UniquePtr{Type},

        ptr := ..malloc(Type.[byte_size]).[cast ?\[var]Type];
        [result] := UniquePtr{Type}(
                ptr=ptr
            );   
        [this].ptr.[inplace_initialize placement.[invoke]];
    ];

    [destructor         
        [this].ptr.[content].[inplace_destroy];
        ..free([this].ptr);
        [this].[drop];
    ];

];

[no_stable_address]
[class MyClass,
    { val:[single] <}

    [destructor
        [this].[drop];
    ];
];

[entry
    uptr := ..UniquePtr{..NoAutoDrop}.create(
            ..MyClass(3.14).[emplace]
        );
    [result] := 0;
];