

opaque mangle::malloc
[function malloc, (size:USize<)Ptr@var\Void];

opaque mangle::free
[function free, (ptr:Ptr@var\Void<)Void];

template::{ Type:symbol<}
constraint::(Type.[is_type])
[class UniquePtr,
    { ptr:Ptr@var\Type <},

    public[layout_constructor];

    public inline
    template::{Placement:symbol<}
    constraint::Placement.[is_placement_type Type]
    [function create, 
        (placement:Placement<)var\UniquePtr{Type}, result,

        ptr := malloc(Type.[byte_size]).[cast ?var\Type];
        result <:= UniquePtr{Type}(
                ptr=ptr
            );   
        this.ptr.[inplace_init placement.[invoke]];
    ];

    public[destructor         
        this.ptr.[content].[inplace_destroy];
        free(this.ptr);
        this.[forget];
    ];

];

[class MyClass,
    { val:Single <},

    public[layout_constructor];
];

[main ()SInt,
    uptr := UniquePtr{MyClass}.create(
            MyClass(3.14).[emplace]
        );
    0.[return];
];