[function [main], ()[signed_integer],
    // var single floating point number
    var :\[var][single]= 0;

    // var pointer to var single float (? is pointer)
    var_ptr :\[var]?\[var][single]= var.\[var][address];

    var_ptr.[content] = 1;

    var_copy := var_ptr.[content];

    var_ptr = [null];

    [result] := var_copy.[cast [signed_integer 32]];
];