[main ()SInt, result,
    // mut single floating point number
    mut :mut\Single= 0;

    // mut pointer to mut single float
    mut_ptr :mut\Ptr@mut\Single= mut.mut\[address];

    mut_ptr.[content] = 1;

    mut_copy := mut_ptr.[content];

    mut_ptr = 0.[as Ptr@mut\Single]; // there is no nullptr in requite! This is how you do it, but you should be careful...
    // its this way because some platforms can reference 0 as a valid memory address.
    // want to get people out of habit of using memory address of 0 as sentinal value.
    // std will probably have an Optional reference template wrapper type that may or may not use null values under hood
    // depending on the platform.

    result <:= mut_copy.[cast];
];