// a polymorph is a symbol that contains multiple overloads
// types of polymorphs include classes, interfaces, adapters, functions, global dynamic variables, and global static variables
// this example source shows function polymorphs and how they work. other kinds are similar but a bit different.
// for example, classes have layouts instead of signatures. adapters have conformities. 
// interfaces and global variables have no tag. they only have at most one overload in their no template implementation.

// templates refeer to declarations with template attributes

[template]::{> NUM:[signed_integer] <}
[weight]::3
[function getNum, ()[signed_integer],
    [result] <:= NUM;
];

// templates have different overloads attached to them, one for each specialization

// declarations without a template attribute are attached directly to the polymorph

[function getNum, ()[signed_integer],
    [result] <:= 0;
];

[function getNum, (> num:[signed_integer] <)[signed_integer],
    [result] <:= num;
];

// store polymorph in variable
[static][global] poly := getNum.[polymorph];

// get overload with no args.
[static][global] noArgs := getNum.[polymorph].[resolve ()[signed_integer]];

// get overload from variable containing polymorph
[static][global] noArgs1 := poly.[resolve ()[signed_integer]];

// get specialization with signature and given template args
[static][global] templateNoArgs := getNum{ NUM=0 }.[resolve ()[signed_integer]];

// loop over all template specializations of polymorph
[static]
[for getNum.[polymorph].[weight_level_range], [static] weight_level := [value],
    // loop over all templates of weight level
    [static]
    [for weight_level.[template_range], [static] template := [value],
        [static]
        [for template.[specialization_range], [static] specialization := [value],
            // etc
        ];
    ];
];

// loop over all overloads of polymorph
[static]
[for getNum.[polymorph].[overload_range], [static] implementation := [value],
    // etc
];