[opaque][mangle]::printf
[function printf, (> format:?\[no_var][utf8], [variadic] vargs:[variadic_arguments_type]<)[void]];

[mangle]::main
[function [noname], ()[signed_integer],
    printf("Hello, %s! I am %d.", [variadic_arguments "world", 30]);

    [result] := 0;
];