[namespace name,
    [function func0, ()[void],
    ];

    [function func0, (int:[fast_signed_integer 32]<)[fast_signed_integer 32],
    
    ];
];

@global @static
myFuncFromName := name.func0;

[namespace name,
    [function func0, (float:[single]<)[single],
        [result] := 0;
    ];
];

@global
global := myFuncFromName(2.[as [single]]);

@auto_drop
[class MyClass,

    [method func1, ()[void],
    
    ];

    [function func1, ()[void],
    
    ];
];

@global @static
myExtension := MyClass.func1.[as_extension];

@global @static
myOtherFunc := MyClass.func1;

[entry
    class := MyClass();
    class->.myExtension(); // call it like an extension method
    MyClass->.myExtension(); // not callable as extension function
    .myOtherFunc(); // call it standalone
    [result] := 0;
];