[function myFunction, ( 
        positional:[single]=0.0,
        >positional_and_named:[single]=0.0<,
        named:[single]=0.0,
        |locked:[single]=0.0
    )[void],
    [result] := positional + positional_and_named + named + locked;
];

[main
    // calling directly from ..myFunction
    // default values are used
    // locked parameters cannot be set
    // parameter marks apply
    a := ..myFunction();
    b := ..myFunction(1.0);
    b := ..myFunction(1.0, 2.0);
    c := ..myFunction(1.0, positional_and_named);
    d := ..myFunction(1.0, named=2.0);
    e := ..myFunction(1.0, named=2.0, positional_and_named=3.0);
    f := ..myFunction(1.0, 2.0, named=3.0);
    g := ..myFunction(1.0, positional_and_named=2.0, named=3.0);

    // call from a pointer to ..myFunction
    ptr := ..myFunction.[procedure_address];
    // default values are forgotten
    // locked parameters are unlocked
    // positional and name passing rules still respected
    h := ptr(1.0, 2.0, named=3.0, locked=4.0);

    // procedure pointers can be written explicitly
    // signatures are symbols, but they are not types!
    // need to convert to a procedure_type with .[type] reflection.
    // note that there is no need to specify names for parameters that are only positional and never named
    // note that parameters that can be named must have name specified
    // the actual order of the parameters does matter!

    [static] Signature := ([single],> positional_and_named:[single]<, named:[single],| locked:[single])[void];
    [static] ProcedureType := Signature.[type];

    // .[procedure_address] returns a function pointer. Note need to make the ProcedureType a pointer with ?
    other_ptr :?ProcedureType= ..myFunction.[procedure_address];

    // you can use procedure_cast reflection to cast to different ptr type
    // arguments must be in the same order
    [static] RemixType :=
        (
            (
               > 
               a:[single],
               b:[single],
               c:[single],
               d:[single]
            )[void]
        ).[type];
    
    remix_ptr :?RemixType= ..myFunction.[procedure_address].[procedure_cast];

    // you can make positional passing order different than the underlying order by using [location] attribute
    // note that any arguments with [variadic] attribute are always in the last location even if no location is specified
    // for the following, a is positional_and_named, b is positional, c is locked, and d is named
    [static] ReorderType := 
        (
            (
                [location]::1 a:[single],
                [location]::0 b:[single],
                [location]::3 c:[single],
                [location]::2 d:[single]
                <
            )[void]
        ).[type];
    
    reordered_ptr :?ReorderType= ..myFunction.[procedure_address].[procedure_cast];

    [result] := 0;  
];