[function myFunction, ( 
        positional:[single]=0.0,
        >positional_and_named:[single]=0.0<,
        named:[single]=0.0,
        |locked:[single]=0.0
    )[single],
    [result] <:= positional + positional_and_named + named + locked;
];

[function myOtherFunction, ( 
        positional:[single]=0.0,
        >positional_and_named:[single]=0.0<,
        named:[single]=0.0,
        |locked:[single]=0.0
    )[single],
    [result] <:= 0;
];

[function myThirdFunction, ( 
        positional:[single]=0.0,
        >positional_and_named:[single]=0.0<,
        named:[single]=0.0 * 0.0,
        |locked:[single]=0.0
    )[single],
    [result] <:= 0;
];

[function myFourthFunction, ( 
        first_arg:[single]=0.0,
        >positional_and_named:[single]=0.0<,
        named:[single]=0.0,
        |locked:[single]=0.0
    )[single],
    [result] <:= 0;
];


[function [main], ()[signed_integer],
    // calling directly from myFunction
    // default values are used
    // locked parameters cannot be set
    // parameter marks apply
    a := myFunction();
    b := myFunction(1.0);
    b := myFunction(1.0, 2.0);
    c := myFunction(1.0, positional_and_named);
    d := myFunction(1.0, named=2.0);
    e := myFunction(1.0, named=2.0, positional_and_named=3.0);
    f := myFunction(1.0, 2.0, named=3.0);
    g := myFunction(1.0, positional_and_named=2.0, named=3.0);

    // call from a pointer to myFunction
    ptr :\[var]= myFunction.[function_address];
    // you can call from ptr just like myFunction
    h := ptr(1.0, 2.0, named=3.0, locked=4.0);
    i := ptr();
    j := ptr(1.0);
    k := ptr(1.0, 2.0);
    l := ptr(1.0, positional_and_named);
    m := ptr(1.0, named=2.0);
    n := ptr(1.0, named=2.0, positional_and_named=3.0);
    o := ptr(1.0, 2.0, named=3.0);
    p := ptr(1.0, positional_and_named=2.0, named=3.0);

    // can assign different function to variable if its [var] and has EXACTLY the same signature.
    // the default values need to have identical expressions when situated.
    ptr = myOtherFunction.[function_address];
    ptr();

    // type is different even if default value evaluates to the same result.
    // ptr = myThirdFunction.[procedure_address]; 
    // this would result in compile error because named parameter's default value is wrong.
    // its wrong even though it still evaluates to 0.
    // need to use signature_cast
    ptr = myThirdFunction.[function_address].[signature_cast];
    ptr();
    
    // need to cast if parameters are named differently
    ptr = myFourthFunction.[function_address].[signature_cast];
    ptr();

    [result] <:= 0;  
];