// templates refeer to declarations with template modifiers

template::{> NUM:SInt <}
weight::3
[procedure getNum, ()SInt, result,
    result <:= NUM;
];

// templates have different overloads attached to them, one for each specialization

// declarations without a template modifier are attached directly to polymorph

[procedure getNum, ()SInt, result,
    result <:= 0;
];

[procedure getNum, (> num:SInt <)SInt, result,
    result <:= num;
];

// get overload with no args.
compile_time noArgs := getNum.[resolve_procedure ()SInt];

// get specialization with signature and given template args
compile_time templateNoArgs := getNum{ NUM=0 }.[resolve_procedure ()SInt];

// loop over all template specializations of polymorphs found through alias
static
[for getNum.[template_range], static template := value,
    static
    [for template.[specialization_range], static specialization := value,
        // etc
    ];
];

// loop over all overloads of all polymorphs of alias
[for getNum.[overload_range], static overload := value,
    // etc
];