// a polymorph is a symbol that contains multiple overloads
// types of polymorphs include classes, interfaces, adapters, functions, common dynamic variables, and common static variables
// this example source shows function polymorphs and how they work. other kinds are similar but a bit different.
// for example, classes have layouts instead of signatures. adapters have conformities. 
// interfaces and common variables have no tag. they only have at most one overload in their no template implementation.

// templates refeer to declarations with template modifiers

template::{> NUM:si <}
weight::3
[function getNum, ()si,
    [result] <:= NUM;
];

// templates have different overloads attached to them, one for each specialization

// declarations without a template modifier are attached directly to the polymorph

[function getNum, ()si,
    [result] <:= 0;
];

[function getNum, (> num:si <)si,
    [result] <:= num;
];

// store polymorph in variable
compile_time poly := getNum.[reflect];

// get overload with no args.
compile_time noArgs := getNum.[reflect].[resolve_function ()si];

// get overload from variable containing polymorph
compile_time noArgs1 := poly.[resolve_function ()si];

// get specialization with signature and given template args
compile_time templateNoArgs := getNum{ NUM=0 }.[resolve_function ()si];

// loop over all template specializations of polymorph
static
[for getNum.[reflect].[weight_level_range], static weight_level := [value],
    // loop over all templates of weight level
    static
    [for weight_level.[template_range], static template := [value],
        static
        [for template.[specialization_range], static specialization := [value],
            // etc
        ];
    ];
];

// loop over all overloads of polymorph
static
[for getNum.[reflect].[overload_range], static implementation := [value],
    // etc
];