// you have to specify what you want to import!
// importing false will import the single symbol false.
// importing namespace A will import everything in namespace A that was exported.

[import "safe_export", A];

[main ()SInt,
    // things in top table are not exportable in requite, so the false from safe_export.rq
    does not override the _SneakyMacro.
    still_false := false;
    [result] <:= 0;
];

[table A,
    [function getBool, ()Bool,
        // lazy symbols in same namespace have to be specified with whole path!

        // this still uses the _SneakyMacro so it expands to [true].
        this_is_true := true;
    
        // from this, its clear something funny is going on here since its in a namespace.
        this_is_actually_false := A.true;

        // this is in the same file, but still have to specify full path
        this_is_false := A.VAR;

        [result] <:= this_is_still_true && this_is_actually_false;
    ];

    eager static my_static_var := false;

    // note that full paths nare not required for eager symbols even in namespaces
    lazy compile_time VAR := my_static_var;
];

