[import "std"];

[class MyClass,
    {> [public] var:[signed_integer] },

    [public]
    [function create, (> a:[signed_integer], b:[signed_integer] <)MyClass,
      [result] := MyClass(var=a + b);
    ];  
];

[function [main], ()[signed_integer],
    // create stack
    my_stack :\[var]= std.StackList{MyClass}();
    
    // push back one element
    // emplace will call the function in the future with the given arguments forwarded
    my_stack.pushBack(MyClass.create(1, 2).[emplace]);

    // remove the last element
    my_stack.popBack();
    
    [result] := 0;
];