[import "std"];

// notice how there is no @auto_drop attribute. 
// this means you ahve to manually drop variables of this type when they go out of scope.
@may_move @may_copy
[class NoAutoDrop,
	// this is like a destructor. it takes ownership of what you call it on and then drops it. 
	// if this type had internal resources, they could be released here.
	@public [method destroy, =>, [this].[drop]; ];
];

[entry
	// create stack and destructor for the stack
	// my_stack.destroy() returns a ranger over all elements so each element can be destroyed before the stack memory is freed.
	my_stack := .std.StackList{NoAutoDrop}();
	[destructor my_stack,
		// destructor requires that the lifetime of the target (my_stack) is ended by the end of it.
		[for my_stack.[move].destroy(), value:=[value].[move],
		 	value.[move].destroy();
		];
	];
	
	// push back some elements
	// notice how the elements are moved into the call. if it was copied, then the temporary would have to be manually dropped.
	my_stack.pushBack(NoAutoDrop().[move]);
	my_stack.pushBack(NoAutoDrop().[move]);
	my_stack.pushBack(NoAutoDrop().[move]);
	
	// remove the last element
	// the last element is linearly assigned out. you have to drop the element manually.
	my_stack.popBack().[move].destroy();
	
	call the destructor for my_stack. you have to do this manually. if the lifetime of my_stack does not end, this results in a compiler error.
	my_stack.[destroy];
];