// This is an example of the automatic rq file which gets automatically
// included by the compiler at the start of every requite source file. variables
// are created here which act like keywords, but they are actually just variables.
// the power in this is that you can do variable shadowing to override them with
// user defined variables. this is how requite has no reserved words but yet has
// a lot of keywords.

// the stellarscope is a special scope that is above the top scope so that 
// variables in the top scope can shadow everything in the stellarscope.
[stellarscope

    // to demonstrate the power of this, look at what we can do assigning [compile_time]
    // a variable named compile_time. we can use the variable as a modifier, and so we
    // don't have to write square brackets all over the place throughout the rest of 
    // this file. Its a variable, so it can be shadowed as well. If a programmer
    // makes their own variable named compile_time, then it will override this variable.
    // If the programmer still wants to use compile_time modifier, they can use it 
    // explicitly with square brackets instead of accessing it via this variable.
    [export][compile_time] compile_time := [compile_time];

    // now do the same with [export] so we can simplify wirting that modifier as well.
    [export] compile_time export := [export];

    export compile_time symbol := [symbol];
    export compile_time expression := [expression];
    export compile_time void := [void];
    export compile_time no_return := [no_return];
    export compile_time boolean := [boolean];
    export compile_time half := [half];
    export compile_time single := [single];
    export compile_time double := [double];
    export compile_time quadruple := [quadruple];
    export compile_time binary16 := [binary16];
    export compile_time binary32 := [binary32];
    export compile_time binary64 := [binary64];
    export compile_time binary128 := [binary128];
    export compile_time bfloat16 := [bfloat16];
    export compile_time si := [signed_integer];
    export compile_time si8 := [signed_integer 8];
    export compile_time si16 := [signed_integer 16];
    export compile_time si32 := [signed_integer 32];
    export compile_time si64 := [signed_integer 64];
    export compile_time si128 := [signed_integer 128];
    export compile_time si256 := [signed_integer 256];
    export compile_time si512 := [signed_integer 512];
    export compile_time ui := [unsigned_integer];
    export compile_time ui8 := [unsigned_integer 8];
    export compile_time ui16 := [unsigned_integer 16];
    export compile_time ui32 := [unsigned_integer 32];
    export compile_time ui64 := [unsigned_integer 64];
    export compile_time ui128 := [unsigned_integer 128];
    export compile_time ui256 := [unsigned_integer 256];
    export compile_time ui512 := [unsigned_integer 512];
    export compile_time fsi := [fast_signed_integer];
    export compile_time fsi8 := [fast_signed_integer 8];
    export compile_time fsi16 := [fast_signed_integer 16];
    export compile_time fsi32 := [fast_signed_integer 32];
    export compile_time fsi64 := [fast_signed_integer 64];
    export compile_time fsi128 := [fast_signed_integer 128];
    export compile_time fsi256 := [fast_signed_integer 256];
    export compile_time fsi512 := [fast_signed_integer 512];
    export compile_time fui := [fast_unsigned_integer];
    export compile_time fui8 := [fast_unsigned_integer 8];
    export compile_time fui16 := [fast_unsigned_integer 16];
    export compile_time fui32 := [fast_unsigned_integer 32];
    export compile_time fui64 := [fast_unsigned_integer 64];
    export compile_time fui128 := [fast_unsigned_integer 128];
    export compile_time fui256 := [fast_unsigned_integer 256];
    export compile_time fui512 := [fast_unsigned_integer 512];
    export compile_time lsi := [least_signed_integer];
    export compile_time lsi8 := [least_signed_integer 8];
    export compile_time lsi16 := [least_signed_integer 16];
    export compile_time lsi32 := [least_signed_integer 32];
    export compile_time lsi64 := [least_signed_integer 64];
    export compile_time lsi128 := [least_signed_integer 128];
    export compile_time lsi256 := [least_signed_integer 256];
    export compile_time lsi512 := [least_signed_integer 512];
    export compile_time lui := [least_unsigned_integer];
    export compile_time lui8 := [least_unsigned_integer 8];
    export compile_time lui16 := [least_unsigned_integer 16];
    export compile_time lui32 := [least_unsigned_integer 32];
    export compile_time lui64 := [least_unsigned_integer 64];
    export compile_time lui128 := [least_unsigned_integer 128];
    export compile_time lui256 := [least_unsigned_integer 256];
    export compile_time lui512 := [least_unsigned_integer 512];
    export compile_time sindex := [signed_index];
    export compile_time uindex := [unsigned_index];
    export compile_time saddress := [signed_address];
    export compile_time uaddress := [unsigned_address];
    export compile_time char := [char];
    export compile_time ascii := [ascii];
    export compile_time utf8 := utf8;
    export compile_time variadic_arguments_type := [variadic_arguments_type];
    export compile_time stellarscope := [stellarscope];
    export compile_time c := [c];
    export compile_time top := [top];
    export compile_time no_modifier := [no_modifier];
    export compile_time anchor := [anchor];
    export compile_time resident := [resident];
    export compile_time flank := [flank];
    export compile_time transparent := [transparent];
    export compile_time opaque := [opaque];
    export compile_time private := [private];
    export compile_time public := [public];
    // export
    export compile_time mutable := [mutable];
    export compile_time partially_mutable := [partially_mutable];
    export compile_time constant := [constant];
    export compile_time dynamic := [dynamic];
    export compile_time static := [static];
    export compile_time runtime := [runtime];
    // compile_time
    export compile_time hybrid := [hybrid];
    export compile_time eager := [eager];
    export compile_time lazy := [lazy];
    export compile_time predefined := [predefined];
    export compile_time singleton := [singleton];
    export compile_time capture := [capture];
    export compile_time linked := [linked];
    export compile_time inline := [inline];
    export compile_time standard_mangle := [standard_mangle];
    export compile_time mangle := [mangle];
    export compile_time pad := [pad];
    export compile_time pack := [pack];
    export compile_time equivocal := [equivocal];
    export compile_time likely := [likely];
    export compile_time unlikely := [unlikely];
    export compile_time supported := [supported];
    export compile_time depreciated := [depreciated];
    export compile_time experimental := [experimental];
    export compile_time unstable_address := [unstable_address];
    export compile_time stable_address := [stable_address];
    export compile_time invariadic := [invariadic];
    export compile_time variadic := [variadic];
    export compile_time best_location := [best_location];
    export compile_time location := [location];
    export compile_time template := [template];
    export compile_time overload := [overload];
    export compile_time constraint := [constraint];
    export compile_time default_weight := [default_weight];
    export compile_time weight := [weight];
    export compile_time manual := [manual];
    export compile_time auto := [auto];
    export compile_time direct := [direct];
    export compile_time virtual := [virtual];
    export compile_time ranger := [ranger];
    export compile_time require := [require];
    export compile_time ensure := [ensure];
    export compile_time no_var := [no_var];
    export compile_time partial_var := [partial_var];
    export compile_time var := [var];
    export compile_time no_volatile := [no_volatile];
    export compile_time volatile := [volatile];
    export compile_time no_atomic := [no_atomic];
    export compile_time atomic := [atomic];
    export compile_time no_null_terminate := [no_null_terminate];
    export compile_time null_terminate := [null_terminate];
    export compile_time modifier := [modifier];
    export compile_time var_qualifier := [var_qualifier];
    export compile_time volatile_qualifier := [volatile_qualifier];
    export compile_time atomic_qualifier := [atomic_qualifier];
    export compile_time null_terminate_qualifier := [null_terminate_qualifier];
    export compile_time true := [true];
    export compile_time false := [false];
];