// This is an example of the automatic rq file which gets automatically
// included by the compiler at the start of every requite source file. variables
// are created here which act like keywords, but they are actually just variables.
// the power in this is that you can do variable shadowing to override them with
// user defined variables. this is how requite has no reserved words but yet has
// a lot of keywords.

// the stellarscope is a special scope that is above the top scope so that 
// variables in the top scope can shadow everything in the stellarscope.
[_stellarscope
    // _SneakyMacro symbols are like variables that do pure AST replacement.
    // Wherever you drop a _SneakyMacro, the compiler will automatically
    // expand whatever symbols are in the macro inplace. Note the underscore
    // in front of the symbol kind name. This is here because you can only 
    // declare _SneakyMacro with [_sneaky_macro] statments, which are not 
    // meant to be done by programmers and instead only done in the 
    // stellarscope file. _SneakyMacro are dangerous to be used for things
    // other than this file. One special feature of _SneakyMacro is that
    // they cannot be reflected on, and .[reflect] railcars will reflect
    // on what was expanded. 

    // to demonstrate the power of this, look at what we can do with a
    // _SneakyMacro within the stellarscope file. If we create one that
    // expands export to [export], we can avoid writing the square
    // brackets for the rest of the file. 
    [export][_sneaky_macro_value export, [export]];

    // _SneakyMacro act like keywords, but they can be shadowed so they
    // are not reserved! This is great for readability!

    // Now lets define a ton of sneaky macros so that there can be less square
    // brackets throughout all other requite code files!
    
    export [_sneaky_macro_statement return, return];
    export [_sneaky_macro_value true, [true]];
    export [_sneaky_macro_value false, [false]];
    export [_sneaky_macro_value value, [value]];
    export [_sneaky_macro_value index, [index]];
    export [_sneaky_macro_value this, this];
    // notice how result ihas special modifier [_expand_dynamic_name]. it can 
    // be expanded as a name too! (it can be expanded to be name of
    // dynamic variable being binded). all macros that dont have this value are 
    // ignored when written as a dynamic variable name.
    [_expand_dynamic_name] export [_sneaky_macro_value result, [result]]; 
    export [_sneaky_macro_value callsite, [callsite]];
    export [_sneaky_macro_value Symbol, [Symbol]];
    export [_sneaky_macro_value Expression, [Expression]];    
    export [_sneaky_macro_value Void, [Void]];
    export [_sneaky_macro_value NoReturn, [NoReturn]];
    export [_sneaky_macro_value Bool, [Bool]];
    export [_sneaky_macro_value Half, [Half]];
    export [_sneaky_macro_value Single, [Single]];
    export [_sneaky_macro_value Double, [Double]];
    export [_sneaky_macro_value Quadruple, [Quadruple]];
    export [_sneaky_macro_value Binary16, [Binary16]];
    export [_sneaky_macro_value Binary32, [Binary32]];
    export [_sneaky_macro_value Binary64, [Binary64]];
    export [_sneaky_macro_value Binary128, [Binary128]];
    export [_sneaky_macro_value Bfloat16, [Bfloat16]];
    export [_sneaky_macro_value Int, [Int]];
    export [_sneaky_macro_value Int8, [Int 8]];
    export [_sneaky_macro_value Int16, [Int 16]];
    export [_sneaky_macro_value Int32, [Int 32]];
    export [_sneaky_macro_value Int64, [Int 64]];
    export [_sneaky_macro_value Int128, [Int 128]];
    export [_sneaky_macro_value Int256, [Int256]];
    export [_sneaky_macro_value Int512, [Int512]];
    export [_sneaky_macro_value Int1024, [Int1024]];
    export [_sneaky_macro_value Size, [Size]];
    export [_sneaky_macro_value Index, [Index]];
    export [_sneaky_macro_value Char, [Char]];
    export [_sneaky_macro_value Ascii, [Ascii]];
    export [_sneaky_macro_value Utf8, [Utf8]];
    export [_sneaky_macro_value VariadicArguments, [VariadicArguments]];
    export [_sneaky_macro_value C, [C]];
    export [_sneaky_macro_value Top, [Top]];
    export [_sneaky_macro_statement debug_break, [debug_break]];
    export [_sneaky_macro_statement unreachable, [unreachable]];
    export [_sneaky_macro_value no_modifier, [no_modifier]];
    export [_sneaky_macro_value anchor, [anchor]];
    export [_sneaky_macro_value resident, [resident]];
    export [_sneaky_macro_value flank, [flank]];
    export [_sneaky_macro_value transparent, [transparent]];
    export [_sneaky_macro_value opaque, [opaque]];
    export [_sneaky_macro_value private, [private]];
    // export already declared above!
    export [_sneaky_macro_value mutable, [mutable]];
    export [_sneaky_macro_value partially_mutable, [partially_mutable]];
    export [_sneaky_macro_value constant, [constant]];
    export [_sneaky_macro_value dynamic, [dynamic]];
    export [_sneaky_macro_value static, [static]];
    export [_sneaky_macro_value runtime, [runtime]];
    export [_sneaky_macro_value compile_time, [compile_time]];
    export [_sneaky_macro_value hybrid, [hybrid]];
    export [_sneaky_macro_value eager, [eager]];
    export [_sneaky_macro_value lazy, [lazy]];
    export [_sneaky_macro_value predefined, [predefined]];
    export [_sneaky_macro_value singleton, [singleton]];
    export [_sneaky_macro_value capture, [capture]];
    export [_sneaky_macro_value linked, [linked]];
    export [_sneaky_macro_value inline, [inline]];
    export [_sneaky_macro_value standard_mangle, [standard_mangle]];
    export [_sneaky_macro_value mangle, [mangle]];
    export [_sneaky_macro_value pad, [pad]];
    export [_sneaky_macro_value pack, [pack]];
    export [_sneaky_macro_value equivocal, [equivocal]];
    export [_sneaky_macro_value likely, [likely]];
    export [_sneaky_macro_value unlikely, [unlikely]];
    export [_sneaky_macro_value supported, [supported]];
    export [_sneaky_macro_value depreciated, [depreciated]];
    export [_sneaky_macro_value experimental, [experimental]];
    export [_sneaky_macro_value unstable_address, [unstable_address]];
    export [_sneaky_macro_value stable_address, [stable_address]];
    export [_sneaky_macro_value invariadic, [invariadic]];
    export [_sneaky_macro_value variadic, [variadic]];
    export [_sneaky_macro_value best_location, [best_location]];
    export [_sneaky_macro_value location, [location]];
    export [_sneaky_macro_value template, [template]];
    export [_sneaky_macro_value overload, [overload]];
    export [_sneaky_macro_value constraint, [constraint]];
    export [_sneaky_macro_value default_weight, [default_weight]];
    export [_sneaky_macro_value weight, [weight]];
    export [_sneaky_macro_value manual, [manual]];
    export [_sneaky_macro_value auto, [auto]];
    export [_sneaky_macro_value direct, [direct]];
    export [_sneaky_macro_value virtual, [virtual]];
    export [_sneaky_macro_value ranger, [ranger]];
    export [_sneaky_macro_value require, [require]];
    export [_sneaky_macro_value ensure, [ensure]];
    export [_sneaky_macro_value break, [break]];
    export [_sneaky_macro_value continue, [continue]];
    export [_sneaky_macro_value no_var, [no_var]];
    export [_sneaky_macro_value var, [var]];
    export [_sneaky_macro_value no_volatile, [no_volatile]];
    export [_sneaky_macro_value volatile, [volatile]];
    export [_sneaky_macro_value no_atomic, [no_atomic]];
    export [_sneaky_macro_value atomic, [atomic]];
    export [_sneaky_macro_value no_null_terminate, [no_null_terminate]];
    export [_sneaky_macro_value null_terminate, [null_terminate]];
    export [_sneaky_macro_value no_signedness, [no_signedness]];
    export [_sneaky_macro_value signed, [signed]];
    export [_sneaky_macro_value unsigned, [unsigned]];
    export [_sneaky_macro_value no_optimization, [no_optimization]];
    export [_sneaky_macro_value fast, [fast]];
    export [_sneaky_macro_value least, [least]];
    export [_sneaky_macro_value Modifier, [Modifier]];
    export [_sneaky_macro_value Qualifier, [Qualifier]];
];