[function [main], ()[signed_integer],
    [static] i32 := [signed_integer];
    [static] other_i32 := i32.[synonym];

    var0 :i32= 30;
    var1 :[var]/other_i32= 30;
    var1 = var0; // compile error! no implicit casting between types.

    [result] <:i32= 0;
];