[function [main], ()[signed_integer],
    [result] :\[var]= 0;
    [if
        // statements before tag of if can be static or dynamic
        var0 := 0;
        var1 := 1;
        // the following line ends in comma, so its the tag condition of this if scope.
        var0 == var1, // this fails, so the next line never executes.
        [result] = 1;
    ];
];

[class MyObject, // the class name is not a tag
    // statements before tag of class must be static
    [static] var := 0;
    [static] el := [signed_integer];
    {>[public] arr : var#el<},  // tag is layout of class
];

[function myFunction, // the function name is not a tag
    // statements before tag of function must be static
    [static] ret := [void];
    [static] default := 0;
    (>arg0:[signed_integer]=default, arg1:[signed_integer]=default<)ret, // tag is signature of function
];


