template::{ Type:Symbol <}
constraint::(Type.[is_type])
[proc asSigned, 
    static Signed : = [SInt Type.[byte_size]];
    ( mut:Type <)Signed, result,
    result <:= mut.[bitwise_cast Signed];
];

[main ()SInt, result,
    result <:= asSigned{Single}(3.14);
];