template::{ Type:Symbol <}
constraint::(Type.[is_type])
[function asSigned, 
    static Signed : = [SInt Type.[byte_size]];
    ( var:Type <)Signed, result,
    result <:= var.[bitwise_cast Signed];
];

[main ()SInt, result,
    result <:= asSigned{Single}(3.14);
];