@{> Type:[type], LENGTH:[unsigned] <}
[object Array,
    {>
        data := Type[LENGTH]:[indeterminate]
    <},

    [layout_constructor];

    [constructor];
];

[entry_point

    my_array := Array{[binary32], 64}();

    my_other_array := Array({1, 2, 3, 4});

];