[mangle]::main
[function main, ()[signed_integer],
    my_boolean :\[var]= [true] /\ [false];
    my_boolean = [true] \/ [false];
    my_boolean = ![true];
    my_boolean = !([true] /\ (![false] \/ [true]));
    [result] := 0;
];