[import "std"];

[function [main], ()[signed_integer],
    // for tuple with inferenced type, all parameters of type are nonpositional
    // nonpositional parameters are either name-keyed if name is specified, or type-keyed if name is noname
    // can only be one type-keyed parameter of any given type. this is enforced at compile time.
    // notice that each parameter has a binding with colon. 
    // the binding is required when tuple type is inferenced to specify type attributes per element.
    inferenced := { named:\[var]="I'm name-keyed", [noname]:\[var]="I'm type-keyed" };

    // can determine if tuple has type-keyed value at compile time with .[has] reflection
    [static]
    [if inferenced.[type].[has @[utf8]],
        // can get the value with .[get] reflection
        // errors with .[get] are caught at compile time, so this is very safe.
        type_keyed_text := inferenced.[get @[utf8]];
        std.print(line=type_keyed_text);
        // see captures.rq for more example usage of this feature
    ];

    // parser knows {} is a "layout" when it finds parameter marks between the braces.
    // see parameter_marks.rq
    // layouts are symbols that can be turned into a "tuple type" using .[type] reflection.
    // when a layout is turned into a tuple type, all default values are forgotten and locked parameters are unlocked.
    // layouts are symbols used to define layout of a class or template.
    // think of tuple types like a "subset" of layouts that have less features.
    // layouts are symbols that can be reflected upon, but they are NOT types. Tuple types are types that can be bound to a variable.
    // see object.rq and templates.rq for examples of layouts.

    [static]TupleType := {> x:\[var][single], y:\[var][single], z:\[var][single] <}.[type];

    // explicitly typed tuples must not be created with bindings per element using colon.
    // this is unlike how they are written when the type is inferenced.
    explicit :TupleType= { 0, 1, w=2, z=3 };

    [result] <:= 0;    
];