[entry
    my_tuple := {num=1, "Hello", [true]};
    
    [if my_tuple.[get [boolean]],
        .std.print(line="{my_tuple.[get ^[utf8]]}");
    ];

    layout:={> f:[float], b:[boolean] <};

    tuple0 :layout = { 0.0.[as [float]], [true] };
    tuple1 :layout = { b=[true], f=3.14 };
    
    [result] := my_tuple.num;
];