[implicit_drop]
[class Foo,
    {>
        [pun][public] value : [fast_signed_integer 32],
    <},
];

[class Bar,
    {>
        other_num := 0,
        [pun][public] base := ..Foo(1)
    <}
];

[import "std"];

[entry
    bar := ..Bar(7, 3);

    foo_ref := bar.[pun_down ..Foo].[borrow];

    int := bar.[pun_down [fast_signed_integer 32]];

    bar_ref := foo_ref.[pun_up ..Bar].[borrow];

    ..std.print(line=int);

    [result] := 0;
];