[import "std"];

[class NameData,
    {> @public name:^[utf8] <},
    @public
    [layout_constructor];
];

[entry_point
    @ascribe..NameData(name="Hello, world!")
    var := 0;
    std.print(line="{var.[symbol].[user_attribute NameData].name}");
];