[class MyClass, {}];
gentime VAR := MyClass;

// use .[reflect] to reflect on the variable itself
gentime the_variable := VAR.[reflect];
// use the variable alone to retrieve the reflected symbol stored in it (MyClass).
gentime the_class := VAR;