@{>Type:[type]<}
[variant Nullable, [signed 8],
    none;
    value:Type;
]

[import "std"]

[entry_point
    var := Nullable{[signed]}.none();

    [match var,
        [case none,
            std.print(line="var is none");
        ][case value(val),
            std.print(line="var is {val}");
        ]
    ]

    var = Nullable{[signed]}.value(10);

    std.print(line="the descriminant value is {var.[descriminant]}.");
]