@(template Type::[type])
[variant Nullable, [signed 8],
    none;
    value::Type;
]

[entry_point
    var := Nullable{[signed]}..none();

    [if var.none.[is_alive],
        std..print(line:"its none");
    ]

    var = Nullable{[signed]}..value(10);

    std..print(line:"the descriminant value is {var.[descriminant]}.");
]